version: '3.8'

services:
  backend:
    build:
      context: ./WeatherApi
    ports:
      - "5000:8080"
    environment:
      - OTEL_SERVICE_NAME=WeatherApi
      - MONGODB_URI=mongodb://admin:adminpassword@mongodb:27017/weather?authSource=admin
      - OTEL_TRACES_EXPORTER=zipkin
      - OTEL_EXPORTER_ZIPKIN_ENDPOINT=http://zipkin:9411/api/v2/spans
      - OTEL_METRICS_EXPORTER=none
      - OTEL_LOGS_EXPORTER=none
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./front
    ports:
      - "3000:80"
    depends_on:
      - backend

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=weather
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=adminpassword
    volumes:
      - mongo-data:/data/db

  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./monitoring/grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - ./monitoring/grafana-dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
      - ./monitoring/grafana-dashboard-1.json:/etc/grafana/provisioning/dashboards/grafana-dashboard-1.json
      - ./monitoring/grafana-dashboard-2.json:/etc/grafana/provisioning/dashboards/grafana-dashboard-2.json
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
    ports:
      - "4000:3000"
    depends_on:
      - zipkin
      - prometheus

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./monitoring/prometheus-config.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - backend

  zipkin:
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"
    depends_on:
      - backend
      - frontend

volumes:
  mongo-data:

  # kong:
  #   image: kong:latest
  #   environment:
  #     - KONG_DATABASE=off
  #     - KONG_PROXY_LISTEN=0.0.0.0:8000, 0.0.0.0:8443 ssl
  #     - KONG_ADMIN_LISTEN=0.0.0.0:8001
  #   ports:
  #     - "8000:8000"
  #     - "8443:8443"
  #     - "8001:8001"