global:
  scrape_interval: 15s 
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'backend'
    static_configs:
      - targets: ['backend:8080']

  - job_name: 'frontend'
    static_configs:
      - targets: ['frontend:3000']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
