apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ../WeatherApi
          ports:
            - containerPort: 8080
          env:
            - name: MONGODB_URI
              value: "mongodb://admin:adminpassword@mongodb:27017/weather?authSource=admin"
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  ports:
    - port: 8080
  selector:
    app: backend
