name: Weather Api

on:
  push: 
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: build WeatherApi
        run: docker build ./WeatherApi --file ./WeatherApi/Dockerfile --tag weatherapi:$(date +$s)