name: Docker build Frontend

on:
  push: 
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Docker build front
        run: docker build ./front --file ./front/Dockerfile --tag front:$(date +%s)