name: Docker build WeatherApi

on:
  push: 
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Docker build WeatherApi
        run: docker build ./back/WeatherApi/WeatherApi --file ./back/WeatherApi/WeatherApi/Dockerfile --tag weatherapi:$(date +%s)